theme = "adwaita-dark"

[editor]
rulers = [81]
cursorline = true
color-modes = true
bufferline = "never"
true-color = true
completion-trigger-len = 1
mouse = false
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = [ "mode", "spinner", "spacer", "version-control" ]
center = [ "file-name", "file-modification-indicator", "spacer", "diagnostics" ]
right = [ "selections", "position-percentage", "position", "file-encoding", "file-type" ]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
V = ["extend_line_below", "select_mode"]

