theme = "yoru"

[editor]
rulers = [80, 100, 120]
cursorline = true
auto-save = true
color-modes = true
bufferline = "multiple"
idle-timeout = 100
completion-trigger-len = 1

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "spacer", "file-base-name"]

[keys.normal]
V = ["extend_line_below", "select_mode"]
