theme = "catppuccin_mocha"

[editor]
shell = ["/usr/bin/fish", "-c"]
rulers = [80, 100, 120]
cursorline = true
auto-save = true
color-modes = true
bufferline = "multiple"
completion-trigger-len = 1
mouse = false

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
right = ["file-type", "separator", "selections", "separator", "primary-selection-length", "separator", "position", "separator", "spacer", "position-percentage", "total-line-numbers"]

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
V = ["extend_line_below", "select_mode"]
