theme = "mocha"

[editor]
rulers = [80]
cursorline = true
color-modes = true
bufferline = "always"
true-color = true
completion-trigger-len = 1
mouse = false
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spacer", "version-control"]
center = ["file-base-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "spinner", "file-type", "file-line-ending",  "spacer", "position-percentage", "position"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
V = ["extend_line_below", "select_mode"]
