theme = "catppuccin_mocha"
# icons = "codeicons"

[editor]
shell = ["fish", "-c"]
rulers = [80, 100, 120]
cursorline = true
auto-save = true
color-modes = true
bufferline = "multiple"
idle-timeout = 250

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

# [editor.icons]
# enable = true

# [editor.statusline]
# left = ["mode", "spinner", "file-type-icon", "file-name"]

[keys.normal]
V = ["extend_line_below", "select_mode"]
