theme = "mocha"

[editor]
shell = ["fish", "-c"]
rulers = [120]
cursorline = true
color-modes = true
bufferline = "always"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "diagnostics"]
right = ["workspace-diagnostics", "selections", "position", "file-line-ending"]

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"
