theme = "dark_modern"

[editor]
rulers = [81]
true-color = true
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = [ "mode", "spinner", "file-base-name" ]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
V = ["extend_line_below", "select_mode"]

