theme = "mocha"
icons = "codeicons"

[editor]
rulers = [80]
cursorline = true
color-modes = true
bufferline = "always"
true-color = true
completion-trigger-len = 1
mouse = false
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-type-icon",
  "file-base-name",
  "file-modification-indicator",
  "spacer",
  "workspace-diagnostics"
]
right = [
  "version-control", 
  "position", 
  "primary-selection-length", 
  "file-line-ending", 
  "file-type", 
  "position-percentage"
]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
wrap-indicator = ""

[keys.normal]
V = ["extend_line_below", "select_mode"]
