theme = "catppuccin_mocha"

[editor]
line-number = "relative"
scrolloff = 5
idle-timeout = 0
rulers = [120]
mouse = false
completion-trigger-len = 1
auto-completion = true
cursorline = true
color-modes = true
bufferline = "always"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
