theme = "mocha"

[editor]
shell = ["/usr/bin/fish", "-c"]
rulers = [120]
cursorline = true
auto-save = true
color-modes = true
bufferline = "multiple"
completion-trigger-len = 1
mouse = false

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "block"

[editor.statusline]
separator = ""
left = ["mode", "spinner", "file-base-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "file-type", "separator", "file-line-ending", "separator", "spacer", "position-percentage", "position"]

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
V = ["extend_line_below", "select_mode"]
