[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright-langserver.config]
python.analysis.autoSearchPaths = true
python.analysis.userLibraryCodeForTypes = true
python.analysis.diagnosticMode = "workspace"
python.linting.mypyEnabled = true

[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"

[language-server.vscode-css-language-server.config]
css.validate = true


[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
soft-wrap = { enable = true, wrap-at-text-width = true }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-"] }

[[language]]
name = "python"
auto-format = true
language-servers =  ["pyright-langserver"]
