[[language]]
name = "css"
language-server = { command = "vscode-css-languageserver", args = ["--stdio"] }
auto-format = true

[[language]]
name = "json"
language-server = { command = "vscode-json-languageserver", args = ["--stdio"] }
auto-format = true

[[language]]
name = "html"
language-server = { command = "vscode-html-languageserver", args = ["--stdio"] }
auto-format = true

[[language]]
name = "markdown"
file-types = ["md", "mdx"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "deno", args = ["fmt", '-'] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "deno", args = ["fmt", '-'] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "deno", args = ["fmt", '-'] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "deno", args = ["fmt", '-'] }
auto-format = true

[[language]]
name = "python"
auto-format = true

[language.language-server]
command = "pyright-langserver"
args = ["--stdio"]

[language.config.python.analysis]
autoSearchPaths = true
userLibraryCodeForTypes = true
diagnosticMode = 'workspace'

[language.config.python.linting]
mypyEnabled = true

[language.formatter]
command = "autopep8"
args = ["-"]
