[[language]]
name = "css"

[language.config]
css.validate = true


[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }


[[language]]
name = "python"
auto-format = true
language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "autopep8", args = ["-"] }

[language.config]
python.analysis.autoSearchPaths = true
python.analysis.userLibraryCodeForTypes = true
python.analysis.diagnosticMode = "workspace"
python.linting.mypyEnabled = true


[[language]]
name = "rust"

[language.config]
assist.importGranularity = "module"
checkOnSave.command = "clippy"
hoverActions.references = true
lens.enumVariantReferences = true
lens.methodReferences = true
lens.references = true
procMacro.enable = true
workspace.symbol.search.kind = "all_symbols"


[[language]]
name = "c-sharp"
language-server = { command = "omnisharp", args = [ "--languageserver" ] }
