[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"
inlayHints.closureCaptureHints.enable = true

[language-server.vscode-css-language-server.config]
css.validate = true

[language-server.ruff-lsp]
command = "ruff-lsp"
config = { settings = { args = [] } }

[language-server.pylyzer.config]
diagnostics = true
inlayHints = true
smartCompletion = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true
rulers = [121]

[[language]]
name = "python"
language-servers = [ "pyright", "ruff-lsp" ]
auto-format = true
