[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[language.config]
css.validate = true


[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-"] }


[[language]]
name = "python"
auto-format = true
language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "autopep8", args = ["-"] }

[language.config]
python.analysis.autoSearchPaths = true
python.analysis.userLibraryCodeForTypes = true
python.analysis.diagnosticMode = "workspace"
python.linting.mypyEnabled = true


[[language]]
name = "rust"

[language.config]
checkOnSave.command = "clippy"
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false


[[language]]
name = "svg"
file-types = ["svg"]
scope = "svg"
injection-regex = "Svg"
indent = { tab-width = 2, unit = "  " }
roots = []
grammar = "xml"
