[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"
inlayHints.closureCaptureHints.enable = true

[language-server.vscode-css-language-server.config]
css.validate = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true
rulers = [121]

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language.formatter]
command = "black"
args = ["--line-length", "79", "--quiet", "-"]
