# User Interface
# ---------------

"ui.background" = { bg = "black" }
"ui.background.separator" = { fg = "white" }

"ui.window" = "line"

"ui.menu" = { bg = "darker_black" }
"ui.menu.selected" = { fg = "black", bg = "pmenu_bg" }
"ui.menu.scroll" = { fg = "grey", bg = "one_bg"}

"ui.popup" = { bg = "darker_black" }
"ui.popup.info" = { fg = "blue", bg = "darker_black" }

"ui.help" = { bg = "darker_black" }

"ui.linenr" = { fg = "grey" }
"ui.linenr.selected" = { fg = "white" }

"ui.selection" = { bg = "one_bg2" }
"ui.selection.primary" = { bg = "one_bg3" }

"ui.text" = "white"
"ui.text.focus" = { fg = "white", bg = "black2" }

"ui.cursor" = { bg = "one_bg3" }
"ui.cursor.primary" = { bg = "black", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "grey", fg = "white" }

"ui.cursorline.primary" = { bg = "lighter_black" }

"ui.cursorcolumn.primary" = { bg = "lighter_black" }

"ui.virtual.indent-guide" = "grey"
"ui.virtual.ruler" = { bg = "one_bg" }
"ui.virtual.wrap" = "grey_fg2"

"ui.highlight" = { bg = "one_bg" }

"special" = { fg = "blue", modifiers = ["bold"] }

# Statusline
# -----------

"ui.statusline" = { bg = "statusline_bg" }
"ui.statusline.inactive" = { fg = "grey_fg2", bg = "statusline_bg" }
"ui.statusline.normal" = { fg = "black", bg = "nord_blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "dark_purple", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "black", bg = "cyan", modifiers = ["bold"] }

# Bufferline

"ui.bufferline" = { fg = "grey_fg2", bg = "darker_black" }
"ui.bufferline.background" = { bg = "lighter_black" }
"ui.bufferline.active" = { fg = "white", bg = "black" }

# Treesitter
# -----------

"tag" = "orange"

"attribute" = "pink"

"type" = "orange"

"type.builtin" = "purple"

"constructor" = "orange"

"namespace" = "pink"

"comment" = { fg = "grey_fg", modifiers = ["italic"] }

"string" = "vibrant_green"

"string.regexp" = "blue"

"constant" = "yellow"

"constant.builtin" = "purple"

"constant.numeric" = "sun"
"constant.character" = "blue"

"keyword" = "purple"

"keyword.control" = "purple"

"keyword.control.import" = "blue"
"keyword.control.repeat" = "orange"
"keyword.control.exception" = "pink"

"variable" = "white"
"variable.builtin" = "purple"
"variable.parameter" = "sun"
"variable.other.member" = "red"

"function" = "blue"
"function.macro" = "dark_purple"
"function.special" = "orange"

"punctuation" = "pink"
"punctuation.special" = "dark_purple"

"label" = "orange"

# Markdown
# ---------

"markup.heading.marker" = { fg = "pink", modifiers = ["bold", "italic"] }
"markup.heading.1" = { fg = "nord_blue", modifiers = ["bold"] }
"markup.heading.2" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.3" = { fg = "dark_purple", modifiers = ["bold"] }
"markup.heading.4" = { fg  = "purple", modifiers = ["bold"] }
"markup.heading.5" = { fg = "cyan", modifiers = ["bold"] }
"markup.heading.6" = { fg  = "teal", modifiers = ["bold"] }

"markup.list" = "orange"

"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }

"markup.link.url" = { fg = "green", underline = { color = "green", style = "line" } }
"markup.link.text" = "purple"

"markup.raw" = "teal"

# Diagnostics
# ------------

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "green", style = "curl" } }
"diagnostic.hint" = { underline = { color = "purple", style = "curl" } }

"error" = "red"
"warning" = "yellow"
"info" = "green"
"hint" = "purple"

# Git diff
# ---------

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"
"diff.delta.moved" = "orange"

[palette]
white = ""
darker_black = ""
black = ""
black2=""
lighter_black = ""
one_bg = ""
one_bg2 = ""
one_bg3 = ""
grey = ""
grey_fg = ""
grey_fg2 = ""
light_grey = ""
red = ""
baby_pink = ""
pink = ""
line = ""
green = ""
vibrant_green = ""
nord_blue = ""
blue = ""
yellow = ""
sun = ""
purple = ""
dark_purple = ""
teal = ""
orange = ""
cyan = ""
statusline_bg = ""
lightbg = ""
pmenu_bg = ""
