inherits = "catppuccin_mocha"

"type" = "blue"

"keyword" = "peach"
"keyword.control.conditional" = "peach"

"function" = "yellow"
"function.builtin" = "red"

"variable.parameter" = "mauve"

"constant.numeric" = "mauve"
"constant.character.escape" = "teal"

"operator" = "peach"

"comment" = { fg = "sapphire60", modifiers = ["italic"] }

"punctuation.bracket" = "pink"

"ui.linenr.selected" = "mauve"
"ui.virtual.ruler" = { bg = "crust" }

[palette]
base = "#010101"
mantle = "#010101"
crust = "#151619"
text = "#cdd6f4"
sapphire60 = "#46778e"
