inherits = "catppuccin_latte"

"ui.virtual.inlay-hint" = { fg = "surface2" }

"ui.popup" = { fg = "subtext1", bg = "mantle" }
"ui.help" = { fg = "subtext0", bg = "mantle" }

"ui.menu" = { fg = "text", bg = "mantle" }
"ui.menu.selected" = { fg = "text", bg = "surface0" }
"ui.menu.scroll" = { fg = "surface1", bg = "mantle" }

"ui.cursor.match" = { bg = "surface1" }
"ui.text.inactive" = { fg = "overlay1" }

"markup.list" = { fg = "sapphire", modifiers = ["bold"] } 
"markup.bold" = { fg = "sapphire", modifiers = ["bold"] }
"markup.italic" = { fg = "green", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "maroon", modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "teal", modifiers = ["underlined"] }
"markup.link.text" = "blue"
"markup.raw" = { fg = "overlay2", bg = "mantle" }
