inherits = "catppuccin_mocha"

"ui.cursor.primary.normal" = { fg = "base", bg = "lavender" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.select" = { fg = "base", bg = "flamingo" }

"ui.cursor.normal" = { fg = "base", bg = "secondary_cursor_normal" }
"ui.cursor.insert" = { fg = "base", bg = "secondary_cursor_insert" }
"ui.cursor.select" = { fg = "base", bg = "secondary_cursor" }

"ui.virtual.inlay-hint" = { fg = "surface1", bg = "mantle" }

"ui.bufferline" = { fg = "subtext0", bg = "mantle" }
"ui.bufferline.active" = { fg = "mauve", bg = "base", underline = { color = "mauve", style = "line" },  modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "crust" }

"attribute" = "blue"

"ui.statusline" = { fg = "subtext1", bg = "mantle" }

"function.builtin" = "blue"

"comment" = { fg = "overlay1", modifiers = ["italic"] }

[palette]
secondary_cursor_normal = "#878ec0"
secondary_cursor_insert = "#7da87e"
