inherits = "catppuccin_mocha"

"ui.statusline.normal" = { fg = "sky", bg = "sky10" }
"ui.statusline.insert" = { fg = "green", bg = "green10" }
"ui.statusline.select" = { fg = "flamingo", bg = "flamingo10" }

"ui.popup" = { fg = "subtext1", bg = "mantle" }
"ui.help" = { fg = "subtext0", bg = "mantle" }

"ui.menu" = { fg = "text", bg = "mantle" }
"ui.menu.selected" = { fg = "text", bg = "surface0" }
"ui.menu.scroll" = { fg = "surface1", bg = "mantle" }

"ui.cursor.match" = { bg = "surface1" }

[palette]
sky10 = "#1d252f"
green10 = "#1f2628"
flamingo10 = "#27232c"
