inherits = "catppuccin_mocha"

"string.special" = "blue"

"punctuation.special" = "sky"

"attribute" = { fg = "teal", modifiers = ["italic"] }

"markup.link.url" = { fg = "rosewater", modifiers = ["italic", "underlined"] }

"diff.delta" = "minus"

"ui.statusline" = { bg = "mantle" }
"ui.statusline.inactive" = { fg = "surface2", bg = "mantle" } 

"ui.bufferline.background" = { bg = "base" }
"ui.bufferline.active" = { fg = "overlay2", bg = "mantle", modifiers = ["bold", "reversed"] }
"ui.bufferline" = { bg = "mantle", fg = "overlay0" }

"ui.selection" = { bg = "surface1" }
"ui.selection.primary" = { bg = "surface2" }

"ui.cursor.select" = { modifiers = ["underlined"] }

# "ui.explorer.file" = { fg = "pink" }
# "ui.explorer.dir" = { fg = "blue" }
