scan_timeout = 10
add_newline = true

[line_break]
disabled = false

format = "$directory$git_branch$git_metrics$git_commit$git_state$git_status$all"

[directory]
style = "cyan"

[git_commit]
tag_symbol = " tag "

[git_branch]
style = "purple"
symbol = ""

[git_metrics]
added_style = "bold yellow"
deleted_style = "bold red"
disabled = false
