theme = "catppuccin_mocha"

[editor]
true-color = true
color-modes = true
line-number = "relative"
idle-timeout = 0
completion-trigger-len = 1
bufferline = "multiple"
cursorline = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = [
  "diagnostics",
  "selections",
  "spacer",
  "position-percentage",
  "file-type",
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-signature-help-docs = true
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "▏"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.whitespace]
render.newline = "all"
characters.newline = "↵"
