[language-server.deno]
command = "deno"
args = ["lsp"]
config = { enable = true, unstable = true, lint = true }

[languager-server.rust-analyzer.config]
check.command = "clippy"

[languager-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vscode-css-language-server.config]
css.validate = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[[language]]
name = "typescript"
language-servers = ["vtsls"]

[[language]]
name = "fish"
auto-format = true
formatter = { command = "fish_indent" }


[[language]]
name = "markdown"
formatter = { command = "deno", args = ["--ext", "md", "-"] }
auto-format = false
rulers = [121]

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language.formatter]
command = "black"
args = ["--line-length", "79", "--quiet", "-"]
